name: Iskandar Giusti
favicon: null
layout_spectrum: 0.4718110098037869
typography_spectrum: 0.26158305001445115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.00885566626675427
  lightness: 0.7907820418477058
  saturation: 0.7698036923538893
  rhythmicContrast: 0.6050236497540027
purpose: []
